name: pytest
on: workflow_dispatch

jobs:

    pytest:
        runs-on: ubuntu-latest
        steps:
            - name: clone repogitory
              run: |
                git clone https://github.com/haru0820/python_github_actions
                cd python_github_acytions

            - name: install pytest
              run: pip install pytest
            - name: run pytest
              run: pytest



